name: Build and test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
    branches:
      - main

env:
  DOTNET_VERSION: 9.0.101

jobs: 
  build_and_test:
    name: Build and test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Release --no-restore
        
      - name: Test
        run: dotnet test -c Release --no-restore --no-build